-- Drop existing tables
DROP TABLE IF EXISTS monthly_settlement CASCADE;
DROP TABLE IF EXISTS payment CASCADE;
DROP TABLE IF EXISTS deduction CASCADE;
DROP TABLE IF EXISTS attendance CASCADE;
DROP TABLE IF EXISTS monthly_entries CASCADE;
DROP TABLE IF EXISTS labour CASCADE;
DROP TABLE IF EXISTS site CASCADE;

-- Create site table
CREATE TABLE site (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  location TEXT,
  status TEXT DEFAULT 'Active',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create labour table
CREATE TABLE labour (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  father_name TEXT,
  mobile TEXT,
  id_number TEXT,
  site_id BIGINT REFERENCES site(id) ON DELETE SET NULL,
  daily_rate NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'Active',
  role TEXT DEFAULT 'Labour',
  is_archived BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create attendance table
CREATE TABLE attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  labour_id BIGINT REFERENCES labour(id) ON DELETE CASCADE,
  month INTEGER NOT NULL,
  year INTEGER NOT NULL,
  attendance_days NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(labour_id, month, year)
);

-- Create deduction table
CREATE TABLE deduction (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  labour_id BIGINT REFERENCES labour(id) ON DELETE CASCADE,
  month INTEGER NOT NULL,
  year INTEGER NOT NULL,
  ration_amount NUMERIC DEFAULT 0,
  pocket_money_amount NUMERIC DEFAULT 0,
  other_deduction_amount NUMERIC DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(labour_id, month, year)
);

-- Create payment table
CREATE TABLE payment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  labour_id BIGINT REFERENCES labour(id) ON DELETE CASCADE,
  payment_date DATE NOT NULL,
  amount NUMERIC NOT NULL,
  mode TEXT,
  notes TEXT,
  month INTEGER,
  year INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create monthly_settlement table (to store settlement data like previous_due)
CREATE TABLE monthly_settlement (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  labour_id BIGINT REFERENCES labour(id) ON DELETE CASCADE,
  month INTEGER NOT NULL,
  year INTEGER NOT NULL,
  attendance_days NUMERIC DEFAULT 0,
  daily_rate NUMERIC DEFAULT 0,
  gross_salary NUMERIC DEFAULT 0,
  ration_amount NUMERIC DEFAULT 0,
  pocket_money_amount NUMERIC DEFAULT 0,
  other_deduction_amount NUMERIC DEFAULT 0,
  total_deductions NUMERIC DEFAULT 0,
  previous_due NUMERIC DEFAULT 0,
  total_payments NUMERIC DEFAULT 0,
  net_salary NUMERIC DEFAULT 0,
  net_payable NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(labour_id, month, year)
);

-- Note: In the app, there is a reference to 'monthly_entries'. I will create it too to match existing code or we can just use monthly_settlement.
CREATE TABLE monthly_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  labour_id BIGINT REFERENCES labour(id) ON DELETE CASCADE,
  month TEXT NOT NULL,
  attendance_days NUMERIC DEFAULT 0,
  daily_rate NUMERIC DEFAULT 0,
  ration NUMERIC DEFAULT 0,
  pocket_money NUMERIC DEFAULT 0,
  other_deduction NUMERIC DEFAULT 0,
  gross_salary NUMERIC DEFAULT 0,
  total_deductions NUMERIC DEFAULT 0,
  net_salary NUMERIC DEFAULT 0,
  payments_made NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(labour_id, month)
);


-- Insert Sample Data
INSERT INTO site (id, name, location) VALUES 
(1, 'Downtown Project', 'City Center'),
(2, 'Riverside Complex', 'North Zone'),
(3, 'Metro Station', 'South Zone');

INSERT INTO labour (id, name, father_name, mobile, id_number, site_id, daily_rate) VALUES
(1, 'Ramesh Kumar', 'Suresh Kumar', '9876543210', 'A101', 1, 500),
(2, 'Suresh Singh', 'Mahesh Singh', '9876543211', 'A102', 1, 550),
(3, 'Manoj Das', 'Raju Das', '9876543212', 'A103', 1, 500),
(4, 'Prakash Yadav', 'Ram Yadav', '9876543213', 'A104', 2, 600),
(5, 'Amit Sharma', 'Vijay Sharma', '9876543214', 'A105', 2, 600),
(6, 'Rahul Verma', 'Anil Verma', '9876543215', 'A106', 2, 550),
(7, 'Vikash Singh', 'Rajendra Singh', '9876543216', 'A107', 3, 700),
(8, 'Sanjay Patel', 'Ravi Patel', '9876543217', 'A108', 3, 650),
(9, 'Rajesh Kumar', 'Dinesh Kumar', '9876543218', 'A109', 3, 500),
(10, 'Deepak Gupta', 'Naresh Gupta', '9876543219', 'A110', 3, 500);

-- Reset sequences for BigInts since we manually inserted ID 1-10
SELECT setval('site_id_seq', (SELECT MAX(id) FROM site));
SELECT setval('labour_id_seq', (SELECT MAX(id) FROM labour));

-- Insert Sample monthly_entries for current month (let's say month June 2026 -> '2026-06')
INSERT INTO monthly_entries (labour_id, month, attendance_days, daily_rate, ration, pocket_money, other_deduction, gross_salary, total_deductions, net_salary, payments_made) VALUES
(1, '2026-06', 20, 500, 1500, 500, 0, 10000, 2000, 8000, 2000),
(2, '2026-06', 22, 550, 2000, 1000, 0, 12100, 3000, 9100, 3000),
(3, '2026-06', 18, 500, 1000, 0, 0, 9000, 1000, 8000, 0);

-- Allow public access for now (if using RLS, needs to be handled properly, we will disable RLS for simplicity as requested "simple labour payment management system")
ALTER TABLE site DISABLE ROW LEVEL SECURITY;
ALTER TABLE labour DISABLE ROW LEVEL SECURITY;
ALTER TABLE attendance DISABLE ROW LEVEL SECURITY;
ALTER TABLE deduction DISABLE ROW LEVEL SECURITY;
ALTER TABLE payment DISABLE ROW LEVEL SECURITY;
ALTER TABLE monthly_settlement DISABLE ROW LEVEL SECURITY;
ALTER TABLE monthly_entries DISABLE ROW LEVEL SECURITY;
