import { Activity, Site, Transaction, Worker } from './types';

export const WORKERS: Worker[] = [
  {
    id: 'w1',
    displayId: '#LF-0982',
    name: 'Rahul Kumar',
    fatherName: 'Ram Kumar',
    mobileNumber: '9876543210',
    identityNumber: 'AADHAAR-1234',
    initials: 'RK',
    type: 'Skilled Labour',
    site: 'Sector 62',
    dailyRate: 850,
    status: 'Active',
    previousDue: 1700,
    presentDays: 26,
    ration: 500,
    pocketMoney: 700,
    otherDeductions: 0,
    paymentsMade: 10000,
  },
  {
    id: 'w2',
    displayId: '#LF-1102',
    name: 'Mukesh Yadav',
    fatherName: 'Shyam Yadav',
    mobileNumber: '8765432109',
    identityNumber: 'AADHAAR-5678',
    initials: 'MY',
    type: 'Plumber',
    site: 'Site-A',
    dailyRate: 850,
    status: 'Inactive',
    previousDue: 0,
    presentDays: 25.5,
    ration: 800,
    pocketMoney: 0,
    otherDeductions: 0,
    paymentsMade: 10000,
  },
  {
    id: 'w3',
    displayId: '#LF-0421',
    name: 'Raju Kumar',
    fatherName: 'Prakash Kumar',
    mobileNumber: '7654321098',
    identityNumber: 'AADHAAR-9012',
    initials: 'RK',
    type: 'Helper',
    site: 'Site-B',
    dailyRate: 850,
    status: 'Active',
    previousDue: 4250,
    presentDays: 24,
    ration: 0,
    pocketMoney: 500,
    otherDeductions: 0,
    paymentsMade: 6000,
  },
  {
    id: 'w4',
    displayId: '#LF-2231',
    name: 'Amit Singh',
    fatherName: 'Balwant Singh',
    mobileNumber: '6543210987',
    identityNumber: 'AADHAAR-3456',
    initials: 'AS',
    type: 'Electrician',
    site: 'Site-B',
    dailyRate: 850,
    status: 'Active',
    previousDue: 850,
    presentDays: 28,
    ration: 1000,
    pocketMoney: 1000,
    otherDeductions: 0,
    paymentsMade: 17000,
  },
];

export const SITES: Site[] = [
  {
    id: 's1',
    name: 'Site A - Downtown Plaza',
    labourCount: 24,
    monthlyPayroll: 142000,
    pendingDue: 18500,
    imageUrl: 'https://images.unsplash.com/photo-1541888086425-d81bb19240f5?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 's2',
    name: 'Site B - Metro Phase 2',
    labourCount: 18,
    monthlyPayroll: 95000,
    pendingDue: 8200,
    imageUrl: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=600&q=80',
  },
];

export const ACTIVITIES: Activity[] = [
  {
    id: 'a1',
    type: 'payment',
    title: 'Payment Released',
    description: '₹12,400 to Site A Labour Group',
    time: '2 hours ago',
  },
  {
    id: 'a2',
    type: 'attendance',
    title: 'Attendance Marked',
    description: 'Site B: 17 present, 1 absent',
    time: 'Morning 09:15 AM',
  },
  {
    id: 'a3',
    type: 'new_labour',
    title: 'New Labour Added',
    description: 'Ramesh Kumar joined Site A',
    time: 'Yesterday',
  },
  {
    id: 'a4',
    type: 'report',
    title: 'Report Generated',
    description: 'Weekly Expenditure Summary',
    time: 'Yesterday',
  },
];

export const LEDGER_TRANSACTIONS: Transaction[] = [
  {
    id: 't1',
    date: '02 Jan',
    title: 'Advance',
    subtitle: 'Site Cash - Sector 62',
    debit: 1000,
    balance: 1000,
    balanceType: 'Dr',
  },
  {
    id: 't2',
    date: '05 Jan',
    title: 'Salary Paid',
    subtitle: 'Dec Arrears - Bank Transfer',
    credit: 5000,
    balance: 4000,
    balanceType: 'Cr',
  },
  {
    id: 't3',
    date: '15 Jan',
    title: 'Rashan',
    subtitle: 'Canteen Deduction',
    debit: 800,
    balance: 3200,
    balanceType: 'Cr',
  },
];
